name: ecm-program-atlas
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - plotly
  - pyarrow
  - openpyxl
  - anndata
  - scanpy
  - pytorch
  - pytest
  - pyyaml
  - pip
  - pip:
      - kaleido
      - xgboost
      - pytorch-tabnet
      - tabicl
